include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    use_build_context_synchronously: false
    use_setters_to_change_properties: false
